# fly.toml app configuration file generated for cmrl-web3-backend on 2023-08-12T11:35:23+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cmrl-web3-backend"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
